let num1 = 0;
let num2 = 1;
let num3 = -1;
let num4 = 2;
let num5 = -2;
console.log(Math.cosh(num1));
console.log(Math.cosh(num2));
console.log(Math.cosh(num3));
console.log(Math.cosh(num4));
console.log(Math.cosh(num5));
