let num1 = 0;
let num2 = 1;
let num3 = -1;
let num4 = 2;
let num5 = -2;
console.log(Math.tanh(num1));
console.log(Math.tanh(num2));
console.log(Math.tanh(num3));
console.log(Math.tanh(num4));
console.log(Math.tanh(num5));
